In [3]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [4]:
tallest = max(fam)
tallest

1.89

In [5]:
round(1.68, 1)

1.7

In [6]:
round(1.68)

2

In [7]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [8]:
sister='liz'

In [9]:
height = 1.73

In [10]:
fam =["liz", 1.73, "emma", 1.68, 
      "mom", 1.71, "dad", 1.89]

list methods

In [15]:
fam.index('mom')

4

In [16]:
fam.count(1.73)

1

str methods

In [17]:
sister.capitalize()

'Liz'

In [18]:
sister.replace('z','sa')

'lisa'

In [19]:
fam.repalce('mom','mommy')

AttributeError: 'list' object has no attribute 'repalce'

In [20]:
sister.index('z')

2

In [21]:
fam.index('mom')

4

In [22]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [23]:
fam.append('me')

append method

In [24]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']

In [25]:
fam.append(1.79)

In [26]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]

In [27]:
type(fam)

list

In [28]:
fam.index('dad')

6

import package

In [29]:
import numpy
array([1,2,3])

NameError: name 'array' is not defined

In [30]:
numpy.array([1,2,3])

array([1, 2, 3])

In [31]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [32]:
from numpy import array
array([1,2,3])

array([1, 2, 3])