In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [2]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)

In [4]:
np_weight/np_height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [5]:
bmi = np_weight/np_height**2

In [6]:
bmi[bmi>23]

array([24.7473475])

In [7]:
type(np_weight)

numpy.ndarray

In [8]:
type(np_height)

numpy.ndarray

In [9]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], 
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

In [10]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [11]:
np_2d.shape

(2, 5)

In [12]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79], 
                  [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [13]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [14]:
np_2d[0][2]

1.71

In [15]:
np_2d[0,2]

1.71

In [16]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [17]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [18]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [19]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [20]:
np_city = np.column_stack((height, weight))

In [21]:
np_city

array([[ 1.99, 64.28],
       [ 1.41, 57.96],
       [ 1.75, 83.46],
       ...,
       [ 2.06, 49.01],
       [ 1.9 , 71.29],
       [ 2.  , 54.67]])

In [22]:
np.mean(np_city[:,0])

1.7519360000000002

In [23]:
np.median(np_city[:,0])

1.75

In [24]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[ 1.        , -0.00291838],
       [-0.00291838,  1.        ]])

In [25]:
np.std(np_city[:,0])

0.200658545554382